name: Build and Deploy to ACI

on:
  pull_request:
    branches:
      - main

env:
  ACR_NAME: acrfeb20

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean packages -DskipTests

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name acrfeb20

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=acrfeb20.azurecr.io/spring-boot-app:${{ github.sha }}
          docker build . -t $IMAGE_NAME
          docker push $IMAGE_NAME

      - name: Deploy to ACI
        run: |
          az container create \
            --resource-group az204labs \
            --name spring-boot-app \
            --image acrfeb20.azurecr.io/spring-boot-app:${{ github.sha }} \
            --registry-login-server acrfeb20.azurecr.io \
            --registry-username $ACR_NAME \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --cpu 1 \
            --memory 1 \
            --os-type Linux \
            --ports 80 \
            --location eastus

      - name: Show logs
        run: |
          az container show \
            --resource-group az204labs \
            --name spring-boot-app \
            --query "{IP:ipAddress.ip}" \
            --output table
          
          
